#pragma once
#include <queue>
#include <chrono>
#include <ctime>
#include <ratio>
#include <thread>
#include <map>
#include "Window.h"
#include "Input.h"
#include "Rendering/Rendering.h"
#include "Mathlibrary/Mathlibrary.h"
#include "CustomMemoryAllocation/Memorymanager.h"
#include "Messaging/Messaging.h"
#include "Meshrenderer.h"
#include "Scene.h"
#include "Logger.h"
#include <GL/glew.h>